### ISSUE TITLE
compute engine is not supporteed

### ISSUE THREAD

**Issue by mikailcetinkaya** [74Labs/node-red-contrib-google#1]
hi,

Great job , thank you.

My node-red is on google compute engine , i want no key json usage.
how to disable key entry ?

Thanks.
Best Regards :)

**Comment by TomStanczyk** [comment]
Hi,

I can make JSON Key as optional, but is it enough? 

Authorization and API call will be like this:

```javascript
var jwtClient = new google.auth.JWT(
  key.client_email, // will be null
  null,
  key.private_key, //will be null
  [scope1, scope2],
  null
);

var api = google[api.name]({
  version: api.version,
  auth: auth,
  project: PROJECT_ID // this one should be added as param ?
});
```

According to [Google API Client docs](https://github.com/google/google-api-nodejs-client#choosing-the-correct-credential-type-automatically) it seems that authorization should be rewritten (current is JWT only).

Best Regards

**Comment by mikailcetinkaya** [comment]
options are always good, 
Thnak you
