### ISSUE TITLE
Events.get

### ISSUE THREAD

**Issue by vnguyen972** [74Labs/node-red-contrib-google#10]
When I tried to call "events.get" with calendarId and eventId as paremeters... I got:

> {
	"kind": "calendar#event",
	"etag": "\"3002097540028000\"",
	"id": "i3he500ien9edgap2dg1fure6o_20180404T150000Z",
	"status": "confirmed",
	"updated": "2017-07-26T05:59:30.014Z",
	"start": {
		"dateTime": "2018-04-04T10:00:00-05:00",
		"timeZone": "America/Chicago"
	},
	"end": {
		"dateTime": "2018-04-04T11:00:00-05:00",
		"timeZone": "America/Chicago"
	},
	"recurringEventId": "i3he500ien9edgap2dg1fure6o",
	"originalStartTime": {
		"dateTime": "2018-04-04T10:00:00-05:00",
		"timeZone": "America/Chicago"
	},
	"visibility": "private",
	"iCalUID": "xxxxxxx@google.com"
}

But when I tested the same call on https://developers.google.com/calendar/v3/reference/events/get
It gave me a fuller data set. The most important thing I was hoping to retrieve was the "summary", "description" and "location".... you know, the event details... what am I missing? is there any other parameter I need to set to get the "full set of result"???

> {
 "kind": "calendar#event",
 "etag": "\"3002097539729000\"",
 "id": "i3he500ien9edgap2dg1fure6o_20180404T150000Z",
 "status": "confirmed",
 "htmlLink": "https://www.google.com/calendar/event?eid=aTNoZTUwMGllbjllZGdhcDJkZzFmdXJlNm9fMjAxODA0MDRUMTUwMDAwWiB2bmd1eWVuOTcyQG0",
 "created": "2017-07-26T05:59:29.000Z",
 "updated": "2017-07-26T05:59:30.014Z",
 "summary": "FW: IT All-Hands Meeting",
 "description": " \r\n\r\n \r\n\r\n-----Original Appointment-----\r\nFrom: Wong, Noel \r\nSent: Wednesday, May 17, 2017 3:05 PM\r\nn",
 "location": "Large Cafeteria",
 "creator": {
  "email": "xxxxx@gmail.com",
  "displayName": "John Doe",
  "self": true
 },
 "organizer": {
  "email": "xxxxx@gmail.com",
  "displayName": "John Doe",
  "self": true
 },
 "start": {
  "dateTime": "2018-04-04T10:00:00-05:00",
  "timeZone": "America/Chicago"
 },
 "end": {
  "dateTime": "2018-04-04T11:00:00-05:00",
  "timeZone": "America/Chicago"
 },
 "recurringEventId": "i3he500ien9edgap2dg1fure6o",
 "originalStartTime": {
  "dateTime": "2018-04-04T10:00:00-05:00",
  "timeZone": "America/Chicago"
 },
 "iCalUID": "xxxxxxx@google.com",
 "sequence": 0,
 "reminders": {
  "useDefault": false,
  "overrides": [
   {
    "method": "popup",
    "minutes": 15
   }
  ]
 }
}

**Comment by vnguyen972** [comment]
I figured it out... after a bit more reading over the "Closed" issues... realized that it was "permission" related.
I went to my calendar and add the "service account" id to the permission list and then it works!!!

Thanks and sorry about the premature entry.

**Comment by TomStanczyk** [comment]
No problem. Great to hear that it worked.
