### ISSUE TITLE
Lost connection to server, reconnecting...

### ISSUE THREAD

**Issue by EnricoSx** [74Labs/node-red-contrib-google#12]
hi, 
i try use i with raspberrypi, i use
**inject->google->debug**
copy json key
**scopes** 
https://www.googleapis.com/auth/fitness.activity.read

**api:** fitness:v1
**operation**: dynamic

when click inject appear
_Lost connection to server, reconnecting..._
internet and dns work correctly

Welcome to Node-RED
===================
1 Jul 11:38:06 - [info] Node-RED version: v0.18.7
1 Jul 11:38:06 - [info] Node.js  version: v8.11.3
1 Jul 11:38:06 - [info] Linux 4.14.50-v7+ arm LE
1 Jul 11:38:09 - [info] Loading palette nodes
1 Jul 11:38:16 - [info] Dashboard version 2.9.4 started at /ui
1 Jul 11:38:18 - [info] Settings file  : /home/pi/.node-red/settings.js
1 Jul 11:38:18 - [info] User directory : /home/pi/.node-red
1 Jul 11:38:18 - [warn] Projects disabled : editorTheme.projects.enabled=false
1 Jul 11:38:18 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
1 Jul 11:38:18 - [info] Server now running at http://127.0.0.1:1880/
1 Jul 11:38:18 - [warn]

**Comment by TomStanczyk** [comment]
Hi,

Can you post some more detailed explanation about what is the payload of inject and where did you saw "Lost connection to server, reconnecting..." (browser, logs?)?

It looks like NodeRED installation or environment problem.
