### ISSUE TITLE
Google Sheets returns invalid_scope

### ISSUE THREAD

**Issue by Ryonez** [74Labs/node-red-contrib-google#19]
I've been trying to get this going, but the lack of documentation is killing me.

I'm passing a json object with the sheet id and range to the API thing.

![image](https://user-images.githubusercontent.com/16157130/51410500-af9a1d00-1bc9-11e9-951c-a50ead82d2ed.png)
![image](https://user-images.githubusercontent.com/16157130/51410518-bb85df00-1bc9-11e9-89c6-ea382efe4e1b.png)

However, I keep getting the following error:
```
Error: invalid_scope: Empty or missing scope not allowed.
```

How do I go about resolving this?

**Comment by Ryonez** [comment]
Fixed the issue myself. For those with a similar issue:

When you set up the google and the API it uses, copy the scopes it tells you it uses from the google node, then edit the configuration node your google node uses:
![image](https://user-images.githubusercontent.com/16157130/51454328-0e69bd00-1da9-11e9-899c-1cf74f9fcc5e.png)

Then, paste/add the missing scopes to the configuration node here:
![image](https://user-images.githubusercontent.com/16157130/51454416-6accdc80-1da9-11e9-835a-f42d34be587b.png)

As I've solved this, I'll be closing the issue.

**Comment by danleighton** [comment]
Hi @Ryonez, would you mind sharing your function block code?

I'd love to see how you configured this please?

**Comment by Ryonez** [comment]
# Requirments:

- The application you use for the google configuration node needs access perms for whatever you need to do on the sheet. Your app should have a service account with an email you can use to give it the perms. 
![image](https://user-images.githubusercontent.com/16157130/61638012-a6127e80-acec-11e9-8f37-80643492c61e.png)
Link to the console if you need it: https://console.developers.google.com

- The id of the spreadsheet. This can be found in the url bar of the sheet.
![image](https://user-images.githubusercontent.com/16157130/61638171-f7227280-acec-11e9-82bd-714912eed31a.png)

# Setup
1. Setup up inject node (Trigger to start everything):
![image](https://user-images.githubusercontent.com/16157130/61636894-ae69ba00-acea-11e9-8505-671b9c016e84.png)

2. Setup function node (This sets the target sheet and ranges):
![image](https://user-images.githubusercontent.com/16157130/61636996-da853b00-acea-11e9-8935-ee64859f86d5.png)
```
msg.payload = {spreadsheetId: "<Google ID of the spreedsheet>", range: "'<Name of sheet>'<range of cells, use !A1:Z99999 for all"};
return msg;
```
EXAMPLE:
```
msg.payload = {spreadsheetId: "1uJmwiwcnZlG4P1jLtVFfdAs0jRK7Yk_hxXZ6YQ-MsFA", range: "'Income'!A1:Z99999"};
return msg;
```

3. Setup google node (This retrieves the target sheet and ranges):
![image](https://user-images.githubusercontent.com/16157130/61637321-67c88f80-aceb-11e9-9cc0-9985483d62ff.png)

4. Set up debug node (just to test it works):
![image](https://user-images.githubusercontent.com/16157130/61637414-98a8c480-aceb-11e9-810e-3291070ab138.png)

5. Test by triggering the inject node. This should output the data you requested into the debug window.
![image](https://user-images.githubusercontent.com/16157130/61637511-c5f57280-aceb-11e9-8cec-b4a1c804118f.png)

Hopefully this helps you.
@danleighton

**Comment by danleighton** [comment]
I shall try that now and see what happens! 

Looks very similar to what I have done. But will try this exactly.

**Comment by Ryonez** [comment]
If there's an issue let me know, but it might be worthwhile starting a new issue.

**Comment by danleighton** [comment]
Brilliant. Thank you. Have now tested.

Once I gave the service account access to the individual spreadsheet, that worked for that instance.

What I am now trying to do is to get admin level access to any spreadsheet, as I need to be able to search and extract data from the whole domain. 

Having done that,  I am going to explore how to get the other APIs working as my main aim is to use this for doing activity reports on the whole GSuite domain.

If you do know how to do the 'global' access to any sheets using 'Super Admin' rights, then I'd be delighted to have any guidance!

Will let you know how I get on! Thank you so much for your help so far. This is such a powerful node which just needs some really good documentation to help it be really outstanding :-)

**Comment by TomStanczyk** [comment]
@danleighton Thanks

I'm little out of time for now but hope to find some time to upgrade googleapis version and provide some more detailed docs.

**Comment by danleighton** [comment]
Hi @TomStanczyk I cannot tell you how helpful that would be!

I am currently trying to configure the discovery api which uses the Dynamic (msg.operation) functionality. I cannot for the life of me work out how to configure it correctly to pass the equivalent of:
`gapi.client.discovery.apis.list`

It is unclear whether I need to pass msg.google.operation or msg.operation
And should it simply be a string? So we tried this... No luck...

```
msg.operation ="apis.list";
msg.payload = {
      name: "appengine",
      preferred: true
};
return msg;
```
And many other variants...

Any quick clues would be gratefully received!

Many thanks for all your hard work on this so far! I am slowly figuring it out!

**Comment by Ryonez** [comment]
> If you do know how to do the 'global' access to any sheets using 'Super Admin' rights, then I'd be delighted to have any guidance!

I do not know how to do this sorry.

It does seem like you have a different issue than the one that this issue was about (and was resolved). At this point I'd recommend starting your own issue specifically for help regarding your particular issue.

**Comment by danleighton** [comment]
> > If you do know how to do the 'global' access to any sheets using 'Super Admin' rights, then I'd be delighted to have any guidance!
> 
> I do not know how to do this sorry.
> 
> It does seem like you have a different issue than the one that this issue was about (and was resolved). At this point I'd recommend starting your own issue specifically for help regarding your particular issue.

Having worked at this, I don't think it is possible to call the Sheets API using a Global user, you can only do it by 'impersonating' a specific user.

**Comment by Ryonez** [comment]
> Having worked at this, I don't think it is possible to call the Sheets API using a Global user, you can only do it by 'impersonating' a specific user.

Probably not, you need the sheet id to use the API it seems.

https://developers.google.com/sheets/api/guides/concepts

Please make your own issue for further help as it's unrelated to this issue.

**Comment by danleighton** [comment]
I will make a new issue :-) Thank you for helping solve the sheets issue!
