### ISSUE TITLE
Missing required parameters

### ISSUE THREAD

**Issue by Isaksson** [74Labs/node-red-contrib-google#3]
Hello.
I have installed the node to Node-RED and I am testing the calendar API but I get this error message when I run the Node.

Error: Missing required parameters: calendarId

How should i pass that parameter to the node?
I have tried with msg.calendarId with no success.

**Comment by TomStanczyk** [comment]
Hello,
Parameters should be passed via msg.payload.
Please, try to set msg.payload.calendarId.

**Comment by Isaksson** [comment]
Hello.
This is what I tried now:
`msg.payload.calendarId = "TheId";
return msg;`
in a function node before the google node.
But still same error, I guess I miss something simple here?

**Comment by TomStanczyk** [comment]
Please try smth like this:
```javascript
msg.payload = {calendarId: "TheId"};
return msg;
```
The `msg.payload` should be an object.

**Comment by Isaksson** [comment]
Thanks. That did solve the issue with calendarId.
But now i get:
`Error: Not Found`
And when i check the google dashboard I could see the request and that it was Error.

Do you have any detailed readme for how to setup this to read the next calendar entry?

**Comment by TomStanczyk** [comment]
Sorry but i don't have any docs related to specific Google API.

This node is simple wrapper for [Google's officially supported Node.js client library for accessing Google APIs](https://github.com/google/google-api-nodejs-client). If you need info for specific operation call please check Google's docs.

Personally, I prefer to check and test all the calls with [Google APIs Explorer](https://developers.google.com/apis-explorer/#p/calendar/v3/) and then move it to NodeRED flows.

**Comment by Isaksson** [comment]
Thanks.
That i already have done, I am using calendar.events.list with Google APIs Explorer and that is working as it should.

In Node-RED I am using this:
API: calendar:v3
Operation: events.list

I have created a Google Connection with the json key from service account at Google API and scopes
https://www.googleapis.com/auth/calendar
https://www.googleapis.com/auth/calendar.readonly

I will test some more but I think I have done it correct?

**Comment by TomStanczyk** [comment]
I think you doing it right on the Node-RED/Google API level.

But... there is one more... Google objects (calendars, drive files, etc.) permissions. 
Please check permissions for your service account. It seems that your service account doesn't have permissions to read calendar's entries. You should add it as for a normal user.

I've just made simple flow to check Calendar API calls and it works.

**Comment by Isaksson** [comment]
Thanks again.
You are absolutely correct, it was a permission issue on that calendar. I corrected that and now it works.
Great Node, thanks for this contribution.

**Comment by declankenny** [comment]
@Isaksson Can you explain how you corrected the calendar permission issue? I am struggling with the same.

Thanks!
