### ISSUE TITLE
empty items?

### ISSUE THREAD

**Issue by dingausmwald** [74Labs/node-red-contrib-google#5]
hey there,
dont know what im doing wrong, fighting with it for days.. but doesnt matter what i do, i get payload with no items when asking for calendar or tasks. Only payload arrives with different stuff but arrays in f.e. items or defaultreminders are empty[0] arrays. Is it me?

**Comment by TomStanczyk** [comment]
Hello,
Provide some more info (flows, config), please.

**Comment by dingausmwald** [comment]
Just testing the node by sending json with inject node to the google node. Settings are made: calendar v3 calendarlist.list which doesnt need parameters. I receive stuff, sometimes related to my account, sometimes more related to the api. Even got some calendar colors once.. Same for the tasks api. Not found for the Ids... Scopes are set right, one, both, doesnt matter. Maybe im to stupid to set the permissions, service accounts, user accounts, invitations and/or sharings right.. this google dashboard is so confusing and buggy. You write its just open the console, create a json key and activate api.. but thats not it, isnt it? Tried everything and deleted all keys 3 times.
Works with the api explorer. Not with node red. Would kill for a how to, last step to finish my project.. just want to create tasks on my google account.

**Comment by dingausmwald** [comment]
okay, i think i got it.. or not. Your node ist just for connecting via service keys (the node.js lib on the other hand has the possibility to use 0Auth2 too). This service key method just provides propper usage for non account services like the url shortener, search and stuff. Service keys just work for drive and calendar with accounts. For things like tasks (what is a part of googlemail, jeeeeez make it more complicated) you need the 0Auth2 authentification. It works somehow, but just spits a list named by the service account email without an error what makes it even more confusing. I wouldve coded it faster by hand than trying this. Hope this text helps somebody, maybe a little hint on your readme would help others coming from "just want to turn on my lights at home" to understand which services are possible to use and which not. Anyway, will there be 0Auth2 support some day?
