### ISSUE TITLE
How to pass request body arguments?

### ISSUE THREAD

**Issue by sbernhard** [74Labs/node-red-contrib-google#7]
For insert calendar event you need to set the body of the message:
https://developers.google.com/google-apps/calendar/v3/reference/events/insert?authuser=1&hl=de

Is this somehow already possible with node-red-contrib-google?

Thank you in advance.

**Comment by sbernhard** [comment]
Solved it! :-)

var msg = {
    payload: { 
        'calendarId': 'yourgooglecalendar@gmail.com',
        'resource': {
            'start': {
                "dateTime": "2017-11-30T09:30:00.00Z"
            },
            'end': {
                "dateTime": "2017-11-30T09:30:00.00Z"
            },
            'summary': 'Hello World'
        }
    }
};

node.log("Payload: "+ msg.payload);
return msg;

**Comment by TomStanczyk** [comment]
Great!
