### ISSUE TITLE
service account role

### ISSUE THREAD

**Issue by goczen** [74Labs/node-red-contrib-google#9]
Hi
I have a question, when I creating the service account, I have to choose a role, what role is the good ?
Norbert

**Comment by TomStanczyk** [comment]
Hi Norbert
I chose _Project->Editor_ role for node testing and it works but I did not investigate this area.
Best regards,
T.

**Comment by goczen** [comment]
Ok, I set it and it works.
I added the service account id to my calendar, so I see my calendar's events in node-red, but how can I list the service account's events in my calendar?
Br.
Norbert

**Comment by TomStanczyk** [comment]
Sorry for delay.

As I remember when you omit id you will get calendar of current user.

T.

**Comment by declankenny** [comment]
@goczen Can you explain how you did this? "I added the service account id to my calendar"?
The only way I can see to add the service account is via an invite, which requires the service account to accept the invite and I have no idea how to access the mailbox for the service account.
I hope I am just being stupid...

**Comment by TomStanczyk** [comment]
OK. Now, as I understand, your question is about how to show service account calendar events in your own Google calendar. It's not a node-red specific question.
Sorry but I don't know how to do it, I think you should check Google calendar service docs.
